### ISSUE TITLE
Create new vm from Datavolume

### ISSUE THREAD

**Issue by heimdull** [kubevirt-manager/kubevirt-manager#56]
When I try to create a new VM using a datavolume there are no volumes available in the UI. I have 2 "local" templates that I would like to select to clone the new VMs disk from.

here is an example how I do this currently (these are visible in the DataVolumes screen)

`  dataVolumeTemplates:
    - metadata:
        name: vm1-disk0
      spec:
        pvc:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 30Gi
          storageClassName: netapp-nas
        source:
          pvc:
            namespace: vm-templates
            name: debian12-genericcloud-qcow2`

**Comment by feitnomore** [comment]
`dataVolumeTemplates` is not supported right now. Can you share one or two example YAMLs so I can try to add this functionality?
Thanks!

**Comment by feitnomore** [comment]
I got examples from documentation. This is on my backlog, I'll add this support and let you know.

**Comment by feitnomore** [comment]
I'm still working on this. Your request made me find a "bad architecture" decision that was made on the code, so I'm kinda refactoring everything to see if I can get a better solution that would also easily accommodate your request.
Thanks for your patience.

**Comment by feitnomore** [comment]
So, just to clarify, you want to clone the DataVolume, not use the existing DataVolume in the VM, right?
Please, share a full YAML, as I am getting confused, because, cloning a DataVolume involves using old DV as source, and a brand new DV as destination.

**Comment by th-2021** [comment]
Maybe something like:
https://kubevirt.io/2020/KubeVirt-VM-Image-Usage-Patterns.html

**Comment by feitnomore** [comment]
Ok, so, the upload is not available, **however**, using DV Template is already done on the **VM Pool** implementation. 
In the **VM Instance** implementation instead of using DVTemplate on the VM yaml itself, the implementation creates the DV and after that refers to it on the yaml, which, at the end is the same thing.
The disk screen on VM offers you 2 options:
1 - Use existing DV
2 - Import from PVC, which basically creates a new DV using the PVC as the source

In the create VM screen, you can use HTTP(s), S3, REGISTRY and PVC as sources for a DV. GCS support is also on the way. So I am not sure what we're missing over here.

**Comment by feitnomore** [comment]
BTW, one of the things I'm working is to introduce a concept of "Images", so that you don't need to fill in the URL everytime you want to create a VirtualMachine from HTTP/S3/GCS/REGISTRY/PVC... I've been working hard on a few new features.
